## sample files
samples: "../samples.tsv"
units: "../units.tsv"
reheader: "../reheader.tsv"
internal_sid: "LIMS"


## references
# human genome
genome_reference:
    basepath: "mirna_ref_abs_path"
    provider: "homo_sapiens"
    release: "hg38"
genome_fasta: "hg38.fasta"
# miRNA dbs index names
mirna_mature: "hsa_mature"
mirna_hairpin: "hsa_hairpin"
pirna: "hsa_pirna"
trna: "hsa_trna"
rrna: "hsa_rrna"
mrna: "hsa_mrna"
other_mirna: "other_mirna"
genome: "hsa_genome"
###
htseq_gff: "../data/ref/gff_file"


rules:
    trim_galore_se:
        params: "--small_rna --dont_gzip --max_length 30 --length 16 "
    multiqc:
        arguments: "--force "
#    mirdeep2_alignment:
#        params: "-e -h -j -l 18 -m -v"
#    mirdeep2_identification:
#        params: "-t hsa -P -b 0 -v"
#    fastq_screen:
#        params: "../data/fastq_screen.config"
    bowtie_mapping:
        strict_params: "-n 0 -l 30 --norc --best --strata -m 1"
        mismatch_params: "-n 2 -l 30 --norc --best --strata -m 1"
        genome_params: "-n 1 -l 30 --norc --best --strata -m 1"
    mir_trace:
        params: "-s hsa"
    htseq:
        params: "-f bam -r pos -t miRNA -i Name"