## sample files
samples: "../samples.tsv"
units: "../units.tsv"
reheader: "../reheader.tsv"
internal_sid: "LIMS"

allow_multimapping: "NO" # YES
## references
# human genome
genome_reference:
    basepath: "mirna_ref_abs_path"
    provider: "homo_sapiens"
    release: "hg38"
genome_fasta: "hg38.fasta"
# miRNA dbs index names
mirna_mature: "hsa_mature"
mirna_mature_fa: "mirbase_mature_full_path.fastq"
mirna_hairpin: "hsa_hairpin"
pirna: "hsa_pirna"
trna: "hsa_trna"
rrna: "hsa_rrna"
mrna: "hsa_mrna"
other_mirna: "other_mirna_mature_from_mirbase"
genome: "hsa_genome"
###
htseq_gff: "gff_file"


rules:
    trim_galore_se:
        arguments: "--small_rna --dont_gzip --max_length 30 --length 16 "
    multiqc:
        arguments: "--force "
    bowtie_mapping:
        strict_params: "-n 0 -l 30 --norc --best --strata -m 1"
        strict_multimap_params: "-n 0 -l 30 --norc -m 10 -a "
        mismatch_params: "-n 2 -l 30 --norc --best --strata -m 1"
        mismatch_multimap_params: "-n 2 -l 30 --norc -m 10 -a "
        genome_params: "-n 1 -l 30 --norc --best --strata -m 1"
    mir_trace:
        params: "-s hsa"
    htseq:
        params: "-f bam -r pos -t miRNA -i Name"